// styles/appStyles.js
import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#e91e63',
  primaryLight: '#f48fb1',
  primaryDark: '#ad4d58',
  accent: '#ff6b9d',
  white: '#fff',
  black: '#000',
  grey: 'rgba(0, 0, 0, 0.7)',
  lightGrey: 'rgba(255, 255, 255, 0.95)',
  extraLightGrey: 'rgba(255, 255, 255, 0.8)',
  brown: 'rgba(119, 79, 56, 0.7)',
  textPrimary: '#774f38',
  modalOverlay: 'rgba(0, 0, 0, 0.7)',
  modalBackground: '#fff',
  modalHeaderBorder: '#f8bbd0',
  statRowBorder: '#ffe0e8',
  detailedStatsBackground: '#fff3f5',
  statsContainerBackground: 'rgba(248, 187, 208, 0.95)',
  purple: '#9c27b0',
  textShadow: 'rgba(0, 0, 0, 0.8)',
  lightGreen: '#4ade80',
  darkGreen: '#22c55e',
  lightYellow: '#fff9e6',
  darkYellow: '#ffa000',
  lightPurple: '#f3e5f5',
  darkPurple: '#d1a5d1',
  statBarText: '#4a1f3d',
  statBarBackground: 'rgba(255, 255, 255, 0.3)',
};

export const appStyles = StyleSheet.create({
  actionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    marginTop: 8,
    width: '100%',
  },
  button: {
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
    elevation: 3,
    minWidth: 85,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  buttonLabel: {
    color: colors.white,
    fontSize: 11,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
  },
  daysAliveContainer: {
    alignItems: 'center',
    backgroundColor: colors.lightGrey,
    borderColor: colors.primaryLight,
    borderRadius: 15,
    borderWidth: 2,
    elevation: 3,
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  daysAliveEmoji: {
    fontSize: 16,
    marginRight: 3,
  },
  daysAliveText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: 'bold',
  },
  evolutionBadgeContainer: {
    paddingHorizontal: 5,
    width: '100%',
  },
  gameButton: {
    backgroundColor: colors.accent,
  },
  mainContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'space-between',
    paddingBottom: 10,
    paddingHorizontal: 12,
  },
  mood: {
    color: colors.primaryDark,
    fontSize: 16,
    fontWeight: 'bold',
  },
  moodContainer: {
    alignItems: 'center',
    backgroundColor: colors.lightGrey,
    borderColor: colors.primaryLight,
    borderRadius: 20,
    borderWidth: 2,
    elevation: 3,
    flexDirection: 'row',
    marginTop: 8,
    paddingHorizontal: 15,
    paddingVertical: 6,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  moodEmoji: {
    fontSize: 18,
    marginRight: 5,
  },
  particle: {
    fontSize: 16,
    position: 'absolute',
    top: -20,
  },
  petContainer: {
    alignItems: 'center',
    marginTop: 5,
  },
  petImage: {
    borderColor: colors.extraLightGrey,
    borderRadius: 70,
    borderWidth: 3,
    height: 140,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    width: 140,
  },
  petImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  resetButton: {
    backgroundColor: colors.primary,
  },
  safeArea: {
    flex: 1,
  },
  sleepButton: {
    backgroundColor: colors.purple,
  },
  statsButton: {
    backgroundColor: colors.primary,
    borderRadius: 15,
    elevation: 3,
    margin: 0,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  statsContainer: {
    backgroundColor: colors.statsContainerBackground,
    borderColor: colors.primaryLight,
    borderRadius: 15,
    borderWidth: 2,
    elevation: 3,
    padding: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    width: '100%',
  },
  title: {
    backgroundColor: colors.brown,
    borderRadius: 15,
    color: colors.white,
    fontSize: 22,
    fontWeight: 'bold',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 4,
    textAlign: 'center',
    textShadowColor: colors.textShadow,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
});

export const modalStyles = StyleSheet.create({
  closeModalButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 15,
    marginHorizontal: 20,
    marginTop: 15,
    paddingVertical: 12,
  },
  closeModalButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  detailedStats: {
    backgroundColor: colors.detailedStatsBackground,
    borderRadius: 15,
    marginBottom: 10,
    marginTop: 15,
    padding: 15,
  },
  detailedStatsTitle: {
    color: colors.primaryDark,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalContainer: {
    backgroundColor: colors.modalBackground,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    maxHeight: '85%',
    paddingBottom: 20,
  },
  modalHeader: {
    alignItems: 'center',
    borderBottomColor: colors.modalHeaderBorder,
    borderBottomWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 10,
    paddingHorizontal: 20,
    paddingTop: 15,
  },
  modalOverlay: {
    backgroundColor: colors.modalOverlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalScroll: {
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  modalTitle: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: 'bold',
  },
  statRow: {
    alignItems: 'center',
    borderBottomColor: colors.statRowBorder,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  statRowLabel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '500',
  },
  statRowValue: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: 'bold',
  },
});
